export const HISTORICO_GANADORES = [
  {
    id: "h1",
    date: "2026-06-12",
    theme: "Luces de La Ciudad",
    winnerName: "city_wildlens",
    winnerInstagram: "city_wildlens",
    location: "Torre Colpatria-Bogota",
    device: "Redmi Note 11s",
    photoUrl: "/zoomcreativo/portafolio/1.jpeg",
    description: "Captura destacada de las luces urbanas desde la Torre Colpatria.",
    techniques: ["Larga exposición móvil", "Filtro nocturno"],
    likes: 0,
    applause: 0
  },
  {
    id: "h2",
    date: "2026-06-11",
    theme: "Hora Dorada",
    winnerName: "diegogomezdags",
    winnerInstagram: "diegogomezdags",
    location: "Buritaca-Magdalena",
    device: "Honor 90",
    photoUrl: "/zoomcreativo/portafolio/2.jpeg",
    description: "Cálidos tonos dorados capturados al atardecer en Buritaca.",
    techniques: ["Hora dorada", "Balance de blancos cálido"],
    likes: 0,
    applause: 0
  },
  {
    id: "h3",
    date: "2026-06-10",
    theme: "Iglesias",
    winnerName: "juanca_castrillon",
    winnerInstagram: "juanca_castrillon",
    location: "El calvario (Aranjuez) Med-Ant",
    device: "Redmi note 13 pro",
    photoUrl: "/zoomcreativo/portafolio/3.jpeg",
    description: "Detalle arquitectónico de la iglesia El Calvario en Aranjuez.",
    techniques: ["Perspectiva contrapicada", "Enfoque geométrico"],
    likes: 0,
    applause: 0
  },
  {
    id: "h4",
    date: "2026-06-09",
    theme: "Reflejos",
    winnerName: "jonatravelcol",
    winnerInstagram: "jonatravelcol",
    location: "San Roque-Antioquia",
    device: "Xiaomi 15 Ultra",
    photoUrl: "/zoomcreativo/portafolio/4.jpeg",
    description: "Simetría perfecta en un reflejo sobre superficie cristalina.",
    techniques: ["Simetría perfecta", "A ras de suelo"],
    likes: 0,
    applause: 0
  },
  {
    id: "h5",
    date: "2026-06-08",
    theme: "Fotografía de calle a color",
    winnerName: "Zoom Creativo",
    winnerInstagram: "",
    location: "El retiro-Antioquia",
    device: "Xiaomi 15 Ultra",
    photoUrl: "/zoomcreativo/portafolio/5.jpeg",
    description: "Captura callejera llena de color y vida en El Retiro.",
    techniques: ["Composición espontánea", "Contraste de color"],
    likes: 0,
    applause: 0
  },
  {
    id: "h6",
    date: "2026-06-07",
    theme: "El clima como protagonista",
    winnerName: "juanca_castrillon",
    winnerInstagram: "juanca_castrillon",
    location: "Belmira- Antioquia",
    device: "Redmi note 13 pro",
    photoUrl: "/zoomcreativo/portafolio/6.jpeg",
    description: "Neblina y atmósfera dramática en los paisajes de Belmira.",
    techniques: ["Fotografía de paisaje", "Control de exposición"],
    likes: 0,
    applause: 0
  }
];
