export const HISTORICO_GANADORES = [
  {
    id: "h1",
    date: "2026-06-12",
    theme: "Luces de La Ciudad",
    winnerName: "city_wildlens",
    winnerInstagram: "city_wildlens",
    location: "Torre Colpatria-Bogota",
    device: "Redmi Note 11s",
    photoUrl: "/zoomcreativo/portafolio/1.jpeg",
    description: "Captura destacada de las luces urbanas desde la Torre Colpatria.",
    techniques: ["Larga exposición móvil", "Filtro nocturno"],
    likes: 0,
    applause: 0
  },
  {
    id: "h2",
    date: "2026-06-11",
    theme: "Hora Dorada",
    winnerName: "diegogomezdags",
    winnerInstagram: "diegogomezdags",
    location: "Buritaca-Magdalena",
    device: "Honor 90",
    photoUrl: "/zoomcreativo/portafolio/2.jpeg",
    description: "Cálidos tonos dorados capturados al atardecer en Buritaca.",
    techniques: ["Hora dorada", "Balance de blancos cálido"],
    likes: 0,
    applause: 0
  },
  {
    id: "h3",
    date: "2026-06-10",
    theme: "Iglesias",
    winnerName: "juanca_castrillon",
    winnerInstagram: "juanca_castrillon",
    location: "El calvario (Aranjuez) Med-Ant",
    device: "Redmi note 13 pro",
    photoUrl: "/zoomcreativo/portafolio/3.jpeg",
    description: "Detalle arquitectónico de la iglesia El Calvario en Aranjuez.",
    techniques: ["Perspectiva contrapicada", "Enfoque geométrico"],
    likes: 0,
    applause: 0
  },
  {
    id: "h4",
    date: "2026-06-09",
    theme: "Reflejos",
    winnerName: "jonatravelcol",
    winnerInstagram: "jonatravelcol",
    location: "San Roque-Antioquia",
    device: "Xiaomi 15 Ultra",
    photoUrl: "/zoomcreativo/portafolio/4.jpeg",
    description: "Simetría perfecta en un reflejo sobre superficie cristalina.",
    techniques: ["Simetría perfecta", "A ras de suelo"],
    likes: 0,
    applause: 0
  },
  {
    id: "h5",
    date: "2026-06-08",
    theme: "Fotografía de calle a color",
    winnerName: "Zoom Creativo",
    winnerInstagram: "",
    location: "El retiro-Antioquia",
    device: "Xiaomi 15 Ultra",
    photoUrl: "/zoomcreativo/portafolio/5.jpeg",
    description: "Captura callejera llena de color y vida en El Retiro.",
    techniques: ["Composición espontánea", "Contraste de color"],
    likes: 0,
    applause: 0
  },
  {
    id: "h6",
    date: "2026-06-07",
    theme: "El clima como protagonista",
    winnerName: "juanca_castrillon",
    winnerInstagram: "juanca_castrillon",
    location: "Belmira- Antioquia",
    device: "Redmi note 13 pro",
    photoUrl: "/zoomcreativo/portafolio/6.jpeg",
    description: "Neblina y atmósfera dramática en los paisajes de Belmira.",
    techniques: ["Fotografía de paisaje", "Control de exposición"],
    likes: 0,
    applause: 0
  },
  {
    id: "h7",
    date: "2026-06-06",
    theme: "Profesiones",
    winnerName: "photo_natural2022",
    winnerInstagram: "photo_natural2022",
    location: "Rio cauca-Achí Bolívar",
    device: "Huawei Y9 prime",
    photoUrl: "/zoomcreativo/portafolio/7.jpeg",
    description: "Captura de labores y oficios cotidianos a la orilla del Río Cauca.",
    techniques: ["Fotografía documental", "Composición de retrato"],
    likes: 0,
    applause: 0
  },
  {
    id: "h8",
    date: "2026-06-05",
    theme: "Fotografía Macro",
    winnerName: "littleworld.28",
    winnerInstagram: "littleworld.28",
    location: "Rio cauca-Achí Bolívar",
    device: "Redmi Note 10 pro",
    photoUrl: "/zoomcreativo/portafolio/8.jpeg",
    description: "Detalles imperceptibles a simple vista revelados por lente macro.",
    techniques: ["Enfoque macro selectivo", "Iluminación natural"],
    likes: 0,
    applause: 0
  },
  {
    id: "h9",
    date: "2026-06-04",
    theme: "Agua",
    winnerName: "andreyyusepy",
    winnerInstagram: "andreyyusepy",
    location: "Eje Ambiental",
    device: "Honor X8c",
    photoUrl: "/zoomcreativo/portafolio/9.jpeg",
    description: "Texturas dinámicas y reflejos sobre el flujo del agua.",
    techniques: ["Congelado de movimiento", "Reflejos dinámicos"],
    likes: 0,
    applause: 0
  },
  {
    id: "h10",
    date: "2026-06-03",
    theme: "Paisajes",
    winnerName: "Zoom Creativo",
    winnerInstagram: "",
    location: "Páramo de Guacheneque",
    device: "Nokia 6.2",
    photoUrl: "/zoomcreativo/portafolio/10.jpeg",
    description: "La imponencia y paz de la naturaleza en el Páramo de Guacheneque.",
    techniques: ["Composición horizontal", "Profundidad de campo"],
    likes: 0,
    applause: 0
  },
  {
    id: "h11",
    date: "2026-06-02",
    theme: "Retrato Urbano",
    winnerName: "juanca_castrillon",
    winnerInstagram: "juanca_castrillon",
    location: "Moravia - Medellin",
    device: "Redmi note 13 pro",
    photoUrl: "/zoomcreativo/portafolio/11.jpeg",
    description: "Retrato enmarcando la identidad cultural y urbana del barrio Moravia.",
    techniques: ["Encuadre de retrato", "Luz ambiente de calle"],
    likes: 0,
    applause: 0
  },
  {
    id: "h12",
    date: "2026-06-01",
    theme: "Manos",
    winnerName: "fernandocastanedabedoya",
    winnerInstagram: "fernandocastanedabedoya",
    location: "Bogota",
    device: "IPhone 11",
    photoUrl: "/zoomcreativo/portafolio/12.jpeg",
    description: "La expresividad y textura de las manos como portadoras de historia.",
    techniques: ["Enfoque selectivo", "Fotografía en detalle"],
    likes: 0,
    applause: 0
  },
  {
    id: "h13",
    date: "2026-05-31",
    theme: "Retrato de Alter Ego",
    winnerName: "diegogomezdags",
    winnerInstagram: "diegogomezdags",
    location: "Bogota",
    device: "Honor 90",
    photoUrl: "/zoomcreativo/portafolio/13.jpeg",
    description: "Retrato conceptual explorando identidades y alter egos.",
    techniques: ["Retrato conceptual", "Iluminación de contraste"],
    likes: 0,
    applause: 0
  },
  {
    id: "h14",
    date: "2026-05-30",
    theme: "Detalle",
    winnerName: "Zoom Creativo",
    winnerInstagram: "",
    location: "-----",
    device: "Samsung Galaxy A56",
    photoUrl: "/zoomcreativo/portafolio/14.jpeg",
    description: "Enfoque en texturas y formas que suelen pasar desapercibidas.",
    techniques: ["Plano detalle", "Enfoque manual"],
    likes: 0,
    applause: 0
  },
  {
    id: "h15",
    date: "2026-05-29",
    theme: "Movimiento y Accion",
    winnerName: "Zoom Creativo",
    winnerInstagram: "",
    location: "Bogota",
    device: "Motorola G4",
    photoUrl: "/zoomcreativo/portafolio/15.jpeg",
    description: "La energía de la acción capturada en el momento exacto.",
    techniques: ["Velocidad de obturación rápida", "Composición de acción"],
    likes: 0,
    applause: 0
  },
  {
    id: "h16",
    date: "2026-05-28",
    theme: "Plano Holandes",
    winnerName: "Zoom Creativo",
    winnerInstagram: "",
    location: "Baru",
    device: "Xiaomi 15T",
    photoUrl: "/zoomcreativo/portafolio/16.jpeg",
    description: "La tensión y dinamismo que aporta la inclinación del plano holandés.",
    techniques: ["Plano holandés inclinado", "Ángulo original"],
    likes: 0,
    applause: 0
  },
  {
    id: "h17",
    date: "2026-05-27",
    theme: "Hora Dorada",
    winnerName: "sebasvisual",
    winnerInstagram: "sebasvisual",
    location: "Bogota-Colombia",
    device: "IPhone 16 pro",
    photoUrl: "/zoomcreativo/portafolio/17.jpeg",
    description: "La atmósfera mágica de la hora dorada sobre la silueta urbana.",
    techniques: ["Hora dorada", "Bloqueo de luces altas"],
    likes: 0,
    applause: 0
  }
];
