export const HISTORICO_GANADORES = [
  {
    id: "h1",
    date: "2026-06-11",
    theme: "Reflejos en el Agua",
    winnerName: "Carlos Mendoza",
    winnerInstagram: "carlos_mza_photo",
    photoUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800",
    description: "Capturado justo después de la lluvia en el centro histórico, usando un charco para duplicar la arquitectura colonial y las luces del atardecer.",
    techniques: ["Perspectiva a ras de suelo", "Luz natural de atardecer", "Simetría perfecta"],
    likes: 24,
    applause: 15
  },
  {
    id: "h2",
    date: "2026-06-10",
    theme: "Retratos a Contraluz",
    winnerName: "Sofía Rojas",
    winnerInstagram: "sofi_rojas_lens",
    photoUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
    description: "Silueta dorada capturada en la hora dorada. Aprovechando el destello directo del sol en la lente para un efecto místico.",
    techniques: ["Enfoque manual", "Compensación de exposición (-1.3)", "Uso de la hora dorada"],
    likes: 31,
    applause: 22
  },
  {
    id: "h3",
    date: "2026-06-09",
    theme: "Geometría Urbana",
    winnerName: "Javier Ortiz",
    winnerInstagram: "javi.ortiz.click",
    photoUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
    description: "Líneas diagonales limpias formadas por la escalera de caracol de un edificio moderno. El blanco y negro resalta el contraste de sombras.",
    techniques: ["Conversión a blanco y negro", "Regla de tercios", "Perspectiva cenital"],
    likes: 19,
    applause: 10
  },
  {
    id: "h4",
    date: "2026-06-08",
    theme: "Texturas de la Naturaleza",
    winnerName: "María Valentina",
    winnerInstagram: "mvale.captures",
    photoUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=800",
    description: "Macro de una hoja con gotas de rocío matutino. Cada gota actúa como un pequeño lente amplificando la textura interna de la hoja.",
    techniques: ["Modo Macro móvil", "Foco selectivo", "Iluminación difusa de mañana"],
    likes: 28,
    applause: 19
  },
  {
    id: "h5",
    date: "2026-06-05",
    theme: "Sombras Misteriosas",
    winnerName: "Andrés Silva",
    winnerInstagram: "andres_silvap",
    photoUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800",
    description: "La sombra de un transeúnte proyectada sobre una pared texturizada a las 5 PM. Un momento de misterio en la vida cotidiana.",
    techniques: ["Contraste alto", "Composición minimalista", "Ángulo picado"],
    likes: 22,
    applause: 12
  },
  {
    id: "h6",
    date: "2026-06-04",
    theme: "Minimalismo Cotidiano",
    winnerName: "Camila Duarte",
    winnerInstagram: "camidu_eye",
    photoUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=800",
    description: "Una taza de café solitaria sobre una mesa de madera oscura bajo una sola línea de luz que entra por la ventana.",
    techniques: ["Espacio negativo", "Enfoque selectivo", "Luz lateral"],
    likes: 25,
    applause: 14
  },
  {
    id: "h7",
    date: "2026-06-03",
    theme: "Velocidad y Movimiento",
    winnerName: "Mateo Guerrero",
    winnerInstagram: "mateo_guerrero",
    photoUrl: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800",
    description: "Efecto barrido de un auto de carreras amarillo pasando a toda velocidad. Capturado usando el modo Pro del celular bajando la velocidad de obturación.",
    techniques: ["Modo Pro", "Velocidad de obturación (1/15s)", "Técnica de barrido (panning)"],
    likes: 35,
    applause: 28
  },
  {
    id: "h8",
    date: "2026-06-02",
    theme: "Colores Complementarios",
    winnerName: "Daniela Santos",
    winnerInstagram: "dani_santos_ph",
    photoUrl: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&q=80&w=800",
    description: "Una flor naranja brillante sobre un fondo azul intenso de una pared pintada. El contraste de colores hace que la foto destaque inmediatamente.",
    techniques: ["Teoría del color", "Modo retrato para desenfoque", "Saturación natural"],
    likes: 30,
    applause: 20
  },
  {
    id: "h9",
    date: "2026-06-01",
    theme: "Fotografía Nocturna",
    winnerName: "Lucas Rivas",
    winnerInstagram: "lucas_rivas_night",
    photoUrl: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&q=80&w=800",
    description: "Estelas de luz de vehículos en una avenida transitada desde un puente peatonal. Se utilizó un trípode para celular y modo de larga exposición.",
    techniques: ["Modo Nocturno", "Larga exposición (4s)", "Uso de trípode"],
    likes: 42,
    applause: 35
  },
  {
    id: "h10",
    date: "2026-05-29",
    theme: "Patrones Repetitivos",
    winnerName: "Gabriela Paz",
    winnerInstagram: "gaby_paz_clicks",
    photoUrl: "https://images.unsplash.com/photo-1508962914676-134849a727f0?auto=format&fit=crop&q=80&w=800",
    description: "La fachada de un edificio corporativo con ventanas idénticas que crean un patrón infinito. Una silueta de un ave rompe la monotonía.",
    techniques: ["Ritmo visual", "Punto de interés", "Alineación y cuadrícula"],
    likes: 27,
    applause: 16
  },
  {
    id: "h11",
    date: "2026-05-28",
    theme: "La Hora Azul",
    winnerName: "Alejandro Ruiz",
    winnerInstagram: "alejo_ruiz_ph",
    photoUrl: "https://images.unsplash.com/photo-1518235506717-e1edb117a89b?auto=format&fit=crop&q=80&w=800",
    description: "El skyline de la ciudad iluminado justo 20 minutos después del atardecer, cuando el cielo adquiere un tono azul cobalto profundo.",
    techniques: ["Hora azul", "Cámara ultra angular", "Balance de blancos automático"],
    likes: 33,
    applause: 24
  },
  {
    id: "h12",
    date: "2026-05-27",
    theme: "Retratos de Mascotas",
    winnerName: "Isabella Gómez",
    winnerInstagram: "isa_gomez_pets",
    photoUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=800",
    description: "Un primer plano detallado de la mirada atenta de un gato. Las texturas de sus ojos y pelaje resaltan gracias a la luz que entra de lado.",
    techniques: ["Modo macro", "Luz de ventana", "Perspectiva al nivel de los ojos del sujeto"],
    likes: 39,
    applause: 30
  },
  {
    id: "h13",
    date: "2026-05-26",
    theme: "Detalles en Blanco y Negro",
    winnerName: "Ricardo Vargas",
    winnerInstagram: "ricardo_v_ph",
    photoUrl: "https://images.unsplash.com/photo-1554080353-a576cf803bda?auto=format&fit=crop&q=80&w=800",
    description: "Las manos arrugadas de mi abuelo sosteniendo un reloj antiguo de bolsillo. Una imagen que cuenta una historia de tiempo y generaciones.",
    techniques: ["Fotografía documental", "Alto contraste en B&N", "Enfoque manual en detalles"],
    likes: 45,
    applause: 40
  },
  {
    id: "h14",
    date: "2026-05-25",
    theme: "Arquitectura Histórica",
    winnerName: "Natalia Vega",
    winnerInstagram: "nat_vega_arch",
    photoUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=800",
    description: "Cúpula de la catedral vista desde abajo. La entrada de luz cenital ilumina los detalles tallados de manera impresionante.",
    techniques: ["Simetría radial", "HDR automático activado", "Ángulo contrapicado extremo"],
    likes: 29,
    applause: 18
  },
  {
    id: "h15",
    date: "2026-05-22",
    theme: "Siluetas al Atardecer",
    winnerName: "Santiago Marín",
    winnerInstagram: "santi_marin_photo",
    photoUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&q=80&w=800",
    description: "Un ciclista recortado contra el disco solar del atardecer. Capturado en la playa con exposición bloqueada en las luces altas.",
    techniques: ["Bloqueo AE/AF", "Subexposición manual", "Regla de tercios para el sujeto"],
    likes: 36,
    applause: 25
  }
];
